name: Trigger Mentioning Comment

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review:
    types: [submitted]
  
jobs:
  trigger:
    name: "Trigger"
    runs-on: ubuntu-latest

    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1.1.2
      with:
        token: ${{ secrets.OUTSIDE_COLLABORATORS_TOKEN_BOT }}
        repository: icub-tech-iit/outside-collaborators
        event-type: create_mentioning_comment
        client-payload: '{
                           "repo": "${{ github.repository }}",
                           "event_name": "${{ github.event_name }}",
                           "issue_number": "${{ github.event.issue.number }}",
                           "pr_number": "${{ github.event.pull_request.number }}",
                           "comment_id": "${{ github.event.comment.id }}"
                         }'
        
